#!/usr/bin/env python
""" AWS EC2 Assign Elastic IP

Automatically assign Elastic IPs to AWS EC2 instances. This can be really nice
in auto scaling groups were you need to communicate the external IP's to
third party systems.

APACHE LICENSE 2.0

Copyright 2014 Skymill Solutions

Licensed under the Apache License, Version 2.0 (the "License");
you may not use this file except in compliance with the License.
You may obtain a copy of the License at

   http://www.apache.org/licenses/LICENSE-2.0

Unless required by applicable law or agreed to in writing, software
distributed under the License is distributed on an "AS IS" BASIS,
WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
See the License for the specific language governing permissions and
limitations under the License.
"""
import sys

import aws_ec2_assign_elastic_ip


if __name__ == '__main__':
    try:
        aws_ec2_assign_elastic_ip.main()
    except KeyboardInterrupt:
        sys.exit(0)
    sys.exit(0)

sys.exit(1)
